# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "try 1: $(azurepipelinesserviceprincipaltenantid)"
    echo "try 2: $MY_MAPPED_ENV_VAR"
    echo "try 3: $(azurepipelinesserviceprincipaltenantidfoobar)"
    echo "try 4: $MY_MAPPED_ENV_VAR_FOO"
  displayName: 'Run a multi-line script'
  env:
    MY_MAPPED_ENV_VAR: $(azurepipelinesserviceprincipaltenantid)
    MY_MAPPED_ENV_VAR_FOO: $(azurepipelinesserviceprincipaltenantidfoobar)
