# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    az login --service-principal -u $SP_APPID -p $SP_PW --tenant $SP_TENANTID
    python3 --version
    python3 test/avere_template_deploy.py -p
  displayName: 'Run a python script'
  env:
    servicePrincipalTenant: $(azurepipelinesserviceprincipaltenantid)
    servicePrincipalAppId: $(azurepipelinesserviceprincipalappid)
    servicePrincipalPassword: $(azurepipelinesserviceprincipalsecret)
    adminPassword: $(controllerpassword)
    controllerPassword: $(controllerpassword)
    SP_TENANTID: $(SPTENANTID)
    SP_APPID: $(SPAPPID)
    SP_PW: $(SPPW)

