# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    az login --service-principal -u $SP_APPID -p $SP_PW --tenant $SP_TENANTID
    python3 --version
    python3 test/avere_template_deploy.py
  displayName: 'Run a python script'
  env:
    servicePrincipalTenant: $(azurepipelinesserviceprincipaltenantid)
    servicePrincipalAppId: $(azurepipelinesserviceprincipalappid)
    servicePrincipalPassword: $(azurepipelinesserviceprincipalsecret)
    adminPassword: $(controllerpassword)
    controllerPassword: $(controllerpassword)
    SP_TENANTID: $(SPTENANTID)
    SP_APPID: $(SPAPPID)
    SP_PW: $(SPPW)

- bash: echo "##vso[task.prependpath]/usr/share/miniconda/bin"
  displayName: Add conda to PATH

- bash: conda create --yes --quiet --name myEnvironment python=3.5 
  displayName: Create Anaconda environment

- bash: |
    source activate myEnvironment
    python pip install --upgrade pip setuptools wheel
    conda install -n myEnvironment scipy
  displayName: 'activate env, install tools, install conda libraries'  

- script: |
    source activate myEnvironment
    pip install pytest
    pip install pytest-cov
    pytest test/test-sample.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'junit/test-results.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'