# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    architecture: 'x64'

- script: |
    python3 --version
    pip install --upgrade pip setuptools wheel
    pip install -r test/requirements.txt
    pip install pytest
    pip install pytest-cov
  displayName: 'Install Python Dependencies'

- script: |
    pytest test/test_avere_template_deploy.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  displayName: 'Test Avere vFXT template-based deployment'
  env:
    AVERE_ADMIN_PW: $(controllerpassword)
    AVERE_CONTROLLER_PW: $(controllerpassword)
    AZURE_TENANT_ID: $(SPTENANTID)
    AZURE_CLIENT_ID: $(SPAPPID)
    AZURE_CLIENT_SECRET: $(SPPW)
    AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: 'junit/test-results.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'