# https://aka.ms/yaml
trigger:
- master
- releases/*

variables:
  VFXT_TEST_VARS_FILE: 'pipelines.json'

jobs:
- job: vfxt_template_testing
  timeoutInMinutes: 180
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: |
      mkdir ~/.ssh
      echo $ID_RSA | sed 's/ RSA PRIVATE KEY/RSAPRIVATEKEY/g; s/ /\n/g; s/RSAPRIVATEKEY/ RSA PRIVATE KEY/g' > ~/.ssh/id_rsa
      chmod 600 ~/.ssh/id_rsa
      ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
      ls -al ~/.ssh
    displayName: 'Get SSH keys'
    env:
      ID_RSA: $(pipelines-rsa-priv)

  - script: |
      pip install --upgrade pip setuptools wheel
      pip install -r test/requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      pytest --disable-pytest-warnings test/test_vfxt_template_deploy.py \
        -k test_deploy_template \
        --location $VFXT_DEPLOY_LOCATION \
        --doctest-modules --junitxml=junit/test-results01a.xml
    displayName: 'Test template-based deployment of Avere vFXT'
    condition: and(succeeded(), eq(variables['RUN_DEPLOY'], 'true'))
    env:
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)
      AVERE_CONTROLLER_PW: $(AVERE-CONTROLLER-PW)
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      pytest --disable-pytest-warnings test/test_vfxt_template_deploy.py \
        -k test_no_storage_account_deploy \
        --location $VFXT_DEPLOY_LOCATION \
        --doctest-modules --junitxml=junit/test-results01b.xml
    displayName: 'Test deploy of vFXT without storage'
    condition: and(succeeded(), eq(variables['RUN_EMPTY_STORAGE'], 'true'))
    env:
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)
      AVERE_CONTROLLER_PW: $(AVERE-CONTROLLER-PW)
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      pytest --disable-pytest-warnings test/test_vfxt_template_deploy.py \
        -k test_byovnet_deploy \
        --location $VFXT_DEPLOY_LOCATION \
        --doctest-modules --junitxml=junit/test-results01c.xml
    displayName: 'Test deploy of vFXT with a VNET in a different resource group'
    condition: and(succeeded(), eq(variables['RUN_BYOVNET'], 'true'))
    env:
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)
      AVERE_CONTROLLER_PW: $(AVERE-CONTROLLER-PW)
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      if [ -f $VFXT_TEST_VARS_FILE ]; then
        cat $VFXT_TEST_VARS_FILE
      fi

      pytest --disable-pytest-warnings test/test_vfxt_cluster_status.py \
        -k TestVfxtClusterStatus \
        --doctest-modules --junitxml=junit/test-results02.xml
    displayName: 'Test cluster status, health, etc.'
    condition: succeeded()
    env:
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)
      AVERE_CONTROLLER_PW: $(AVERE-CONTROLLER-PW)
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      pytest --disable-pytest-warnings test/test_vfxt_cluster_status.py \
        -k TestVfxtSupport \
        --doctest-modules --junitxml=junit/test-results03.xml
    displayName: 'Collect vFXT deployment artifacts'
    condition: always()
    env:
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)
      AVERE_CONTROLLER_PW: $(AVERE-CONTROLLER-PW)
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      DEPLOY_ID=$(jq -r .deploy_id $VFXT_TEST_VARS_FILE)
      CONTROLLER_NAME=$(jq -r .controller_name $VFXT_TEST_VARS_FILE)
      T_ARTIFACTS_DIR="vfxt_artifacts_${DEPLOY_ID}"

      echo "DEPLOY_ID: $DEPLOY_ID"
      echo "CONTROLLER_NAME: $CONTROLLER_NAME"
      echo "T_ARTIFACTS_DIR: $T_ARTIFACTS_DIR"

      P_ARTIFACTS_DIR="$BUILD_SOURCESDIRECTORY/test_artifacts"
      mkdir -p $P_ARTIFACTS_DIR
      tar -zcvf ${P_ARTIFACTS_DIR}/vfxt_artifacts_${DEPLOY_ID}.tar.gz ${T_ARTIFACTS_DIR}

      echo "vfxt.log from ${T_ARTIFACTS_DIR}:"
      cat ${T_ARTIFACTS_DIR}/vfxt.log
    displayName: 'Archive deployment artifacts and dump vfxt.log'
    condition: always()

  - script: |
      grep -i -C 5 -e vfxt:ERROR -e exception $BUILD_SOURCESDIRECTORY/test_artifacts/vfxt.log
    displayName: 'Grep errors from vfxt.log (+/- 5 lines)'
    condition: or(failed(), canceled())

  - script: |
      pytest --disable-pytest-warnings test/test_vdbench.py \
        --doctest-modules --junitxml=junit/test-results04.xml
    displayName: 'Test vdbench on Avere vFXT'
    condition: and(succeeded(), eq(variables['RUN_VDBENCH_STEP'], 'true'))
    env:
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      pytest --disable-pytest-warnings test/test_edasim.py \
        --doctest-modules --junitxml=junit/test-results05.xml
    displayName: 'Test edasim on Avere vFXT'
    condition: and(succeeded(), eq(variables['RUN_EDASIM_STEP'], 'true'), eq(variables['RUN_EMPTY_STORAGE'], 'false'))
    env:
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      AZURE_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - task: PublishPipelineArtifact@0
    displayName: 'Publish Pipelines Artifacts (node logs, rolling trace)'
    inputs:
      artifactName: 'testArtifacts'
      targetPath: 'test_artifacts'
    condition: always()

  - script: |
      az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
      RESOURCE_GROUP=$(jq -r .resource_group $VFXT_TEST_VARS_FILE)
      echo "RESOURCE_GROUP: $RESOURCE_GROUP"
      az group delete --yes -n $RESOURCE_GROUP
      if [ "true" = "$RUN_BYOVNET" ]; then
        echo "RESOURCE_GROUP (vnet): ${RESOURCE_GROUP}-vnet"
        az group delete --yes -n "${RESOURCE_GROUP}-vnet"
      fi
    displayName: 'Clean up resource group'
    condition: and(always(), ne(variables['SKIP_RG_CLEANUP'], 'true'))
    env:
      AZURE_TENANT_ID: $(AZURE-TENANT-ID)
      AZURE_CLIENT_ID: $(AZURE-CLIENT-ID)
      AZURE_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: 'junit/test-results*.xml'
      testRunTitle: 'Publish pytest results'
