# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: |
    az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    python3 --version
    python3 -m pip install azure.mgmt.resource
    python3 test/avere_template_deploy.py --skip-az-ops
  displayName: 'Test Avere template deployment'
  env:
    AVERE_ADMIN_PW: $(controllerpassword)
    AVERE_CONTROLLER_PW: $(controllerpassword)
    AZURE_TENANT_ID: $(SPTENANTID)
    AZURE_CLIENT_ID: $(SPAPPID)
    AZURE_CLIENT_SECRET: $(SPPW)
