parameters:
  - name: original_node_count
    displayName: "Original Node Count"
    type: number
    default: 3
    values:
      - 3
      - 14
  - name: scale_up_node_count
    displayName: "Scale Up Node Count +"
    type: number
    default: 2
    values:
      - 2
  - name: region
    displayName: "Region to run pipeline"
    type: string
    default: "eastus"
    values:
      - "eastus"
      - "eastus2"
      - "westus"
      - "westus2"
      - "westeurope"
  - name: run_terraform
    displayName: "Select terraform example to run"
    type: string
    default: "azureblobfiler"
    values:
      - "1-filer"
      - "proxy"
      - "azureblobfiler"
  - name: run_vdbench
    displayName: "Run vdbench"
    type: boolean
    default: true
  - name: run_scale_up
    displayName: "Run scale-up"
    type: boolean
    default: true
  - name: run_scale_down
    displayName: "Run scale-down (only runs if scale-up is selected)"
    type: boolean
    default: false
  
jobs:
- job: Terraform_vFXT
  timeoutInMinutes: 120
  cancelTimeoutInMinutes: 40
  pool:
    vmImage: ubuntu-latest
  steps:  
  - template: templates/setup_ssh.yml
  - template: templates/setup_envars.yml
    parameters:
      run_terraform: ${{ parameters.run_terraform }}
      region: ${{ parameters.region }}
  - template: templates/terraform_setup.yml
    parameters:
      original_node_count: ${{ parameters.original_node_count }}
      run_terraform: ${{ parameters.run_terraform }}
  
  - ${{ if eq(parameters.run_vdbench, true) }}:
    - ${{ if eq(parameters.run_terraform, 'azureblobfiler') }}:
    - template: templates/run_vdbench.yml
      parameters:
        run_terraform: ${{ parameters.run_terraform }}

  - ${{ if eq(parameters.run_scale_up, true) }}:
    - template: templates/terraform_scale_up_down.yml
      parameters:
        original_node_count: ${{ parameters.original_node_count }}
        scale_up_node_count: ${{ parameters.scale_up_node_count }}
        scale: "up"
    - template: templates/terraform_cmd.yml
      parameters: 
        run_terraform: ${{ parameters.run_terraform }}
        cmd_terraform: 'apply'
    
  - ${{ if eq(parameters.run_scale_up, true) }}:
    - ${{ if eq(parameters.run_scale_down, true) }}:
      - template: templates/terraform_scale_up_down.yml
        parameters:
          original_node_count: ${{ parameters.original_node_count }}
          scale_up_node_count: ${{ parameters.scale_up_node_count }}
          scale: "down"
      - template: templates/terraform_cmd.yml
        parameters: 
          run_terraform: ${{ parameters.run_terraform }}
          cmd_terraform: 'apply'
        
  - template: templates/terraform_cmd.yml
    parameters: 
      run_terraform: ${{ parameters.run_terraform }}
      cmd_terraform: 'destroy'

  - template: templates/rg_delete.yml