parameters:
  - name: ORIGINAL_NODE_COUNT
    displayName: "Original Node Count"
    type: number
    default: 3
    values:
      - 3
      - 14
  - name: SCALE_UP_NODE_COUNT
    displayName: "Scale Up Node Count +"
    type: number
    default: 2
    values:
      - 2
  - name: run_terraform
    displayName: "Select terraform example to run"
    type: string
    default: "1-filer"
    values:
      - "1-filer"
      - "proxy"
      - "azureblobfiler"
  - name: run_scale_up
    displayName: "Run scale-up"
    type: boolean
    default: true
  - name: run_scale_down
    displayName: "Run scale-down"
    type: boolean
    default: true

jobs:
- job: Terraform_vfxt
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-latest
  steps:  
  - template: templates/ssh_setup.yml
  - template: templates/cred.yml
    parameters:
      run_terraform: ${{ parameters.run_terraform }}
  - template: templates/terraform_setup.yml
    parameters:
      ORIGINAL_NODE_COUNT: ${{ parameters.ORIGINAL_NODE_COUNT }}
  
  - ${{ if eq(parameters.run_terraform, 'proxy') }}:
    - template: templates/terraform_additional_setup.yml
      parameters:
        run_terraform: ${{ parameters.run_terraform }}
  
  - ${{ if eq(parameters.run_terraform, 'azureblobfiler') }}:
    - template: templates/terraform_additional_setup.yml
      parameters:
        run_terraform: ${{ parameters.run_terraform }}'
  
  - template: templates/terraform_apply.yml
    parameters: 
      run_terraform: ${{ parameters.run_terraform }}

  - ${{ if eq(parameters.run_scale_up, true) }}:
    - template: templates/scale_up_down.yml
      parameters:
        ORIGINAL_NODE_COUNT: ${{ parameters.ORIGINAL_NODE_COUNT }}
        SCALE_UP_NODE_COUNT: ${{ parameters.SCALE_UP_NODE_COUNT }}
        scale: "up"

  - ${{ if eq(parameters.run_scale_down, true) }}:
    - template: templates/scale_up_down.yml
      parameters:
        ORIGINAL_NODE_COUNT: ${{ parameters.ORIGINAL_NODE_COUNT }}
        SCALE_UP_NODE_COUNT: ${{ parameters.SCALE_UP_NODE_COUNT }}
        scale: "down"

  - template: templates/terraform_destroy.yml