parameters:
  - name: ORIGINAL_NODE_COUNT
    displayName: "Original Node Count"
    type: number
    default: 3
    values:
      - 3
      - 14
  
  - name: SCALE_UP_NODE_COUNT
    displayName: "Scale Up Node Count +"
    type: number
    default: 2
    values:
      - 2
  
  - name: run_terraform
    displayName: "Select terraform example to run"
    type: string
    default: "1-filer"
    values:
      - "1-filer"
      - "proxy"
      - "azureblobfiler"
  
  - name: P_RUN_Scale_Up
    displayName: "Run scale-up"
    type: boolean
    default: true

  - name: P_RUN_Scale_Down
    displayName: "Run scale-down"
    type: boolean
    default: true
  
variables:
  _RUN_Scale_Up: $[lower('${{ parameters.P_RUN_Scale_Up }}')]
  _RUN_Scale_Down: $[lower('${{ parameters.P_RUN_Scale_Down }}')]

jobs:
- job: Terraform_vfxt
  timeoutInMinutes: 120
  pool:
    vmImage: ubuntu-latest
  steps:  
  - task: DownloadSecureFile@1
    inputs:
      secureFile: 'id_rsa'
  
  # - task: DownloadSecureFile@1
  #   inputs:
  #     secureFile: 'pip.conf'

  - script: |
      set -e
      # cp $AGENT_TEMPDIRECTORY/pip.conf .
      ln -s $AGENT_TEMPDIRECTORY ~/.ssh
      chmod 600 ~/.ssh/id_rsa
      ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
    displayName: 'SETUP: SSH keys'
    condition: succeeded()
    failOnStderr: true
  
  - script: |
      # az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
      unzip terraform_0.12.25_linux_amd64.zip
      sudo mv terraform /usr/local/bin
      sudo chmod 755 /usr/local/bin/terraform
      
      mkdir -p ~/.terraform.d/plugins
      wget -O ~/.terraform.d/plugins/terraform-provider-avere https://github.com/Azure/Avere/releases/download/tfprovider_v0.9.29/terraform-provider-avere
      chmod 755 ~/.terraform.d/plugins/terraform-provider-avere

      export RESOURCE_GROUP_NAME="tf$(date -u +'%m%dx%H%M%S')"
      echo "##vso[task.setvariable variable=RESOURCE_GROUP_NAME]${RESOURCE_GROUP_NAME}"
      sshkey="$(cat ~/.ssh/id_rsa.pub) azureuser@linuxvm"
      echo "##vso[task.setvariable variable=secret.SSH_KEY;issecret=true]${sshkey}"
      export REGION=westus
      
      cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
      sed -i -E -e "s:vm_ssh_key_data = null:vm_ssh_key_data = \"${sshkey}\":" \
        -e "s/location = \"eastus\"/location = \"${REGION}\"/" \
        -e "s/(([a-z]+)_resource_group_name) = \"[^\"]+\"/\1 = \"${RESOURCE_GROUP_NAME}-\2\"/" \
        -e "s/vfxt_cluster_password = \"VFXT_PASSWORD\"/vfxt_cluster_password = \"${AVERE_ADMIN_PW}\"/" \
        -e 's/vfxt_node_count = 3/vfxt_node_count = ${{ parameters.ORIGINAL_NODE_COUNT }}\n    node_cache_size = 1024\n    node_size = "unsupported_test_SKU"/' main.tf
    displayName: 'Terraform Setup'
    name: setup
    condition: succeeded()
    env:
      # ARM_TENANT_ID: $(AZURE-TENANT-ID)
      # ARM_CLIENT_ID: $(AZURE-CLIENT-ID)
      # ARM_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      # ARM_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)
  
  
  - ${{ if eq(parameters.run_terraform, 'proxy') }}:
    - script: |
        cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
        sed -i "s/storage_account_name = \"storageaccount\"/storage_account_name = \"$RESOURCE_GROUP_NAME\"/" main.tf
      displayName: 'Terraform Proxy setup'
  
  - ${{ if eq(parameters.run_terraform, 'azureblobfiler') }}:
    - script: |
        cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
        sed -i "s/storage_account_name = \"storageaccount\"/storage_account_name = \"$RESOURCE_GROUP_NAME\"/" main.tf
      displayName: 'Terraform Azureblobfiler setup'
  
  - script: |
      az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
      cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
      cat main.tf

      terraform init 
      terraform apply -auto-approve
    displayName: 'Terraform Apply'
    env:
      ARM_TENANT_ID: $(AZURE-TENANT-ID)
      ARM_CLIENT_ID: $(AZURE-CLIENT-ID)
      ARM_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)
      AVERE_ADMIN_PW: $(AVERE-ADMIN-PW)

  - script: |
      cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
      export new_node_count=$(( ${{ parameters.ORIGINAL_NODE_COUNT }} + ${{ parameters.SCALE_UP_NODE_COUNT }} ))
      sed -i "s/vfxt_node_count = ${{ parameters.ORIGINAL_NODE_COUNT }}/vfxt_node_count = ${new_node_count}/" main.tf
      terraform apply -auto-approve
    displayName: 'Terraform - scale up'
    condition: and(not(or(failed(), canceled())), eq(variables['_RUN_Scale_Up'], 'true'))
    env:
      ARM_TENANT_ID: $(AZURE-TENANT-ID)
      ARM_CLIENT_ID: $(AZURE-CLIENT-ID)
      ARM_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
      export new_node_count=$(( ${{ parameters.ORIGINAL_NODE_COUNT }} + ${{ parameters.SCALE_UP_NODE_COUNT }} ))
      sed -i "s/vfxt_node_count = ${new_node_count}/vfxt_node_count = ${{ parameters.ORIGINAL_NODE_COUNT }}/" main.tf
      terraform apply -auto-approve
    displayName: 'Terraform - scale down'
    condition: and(not(or(failed(), canceled())), eq(variables['_RUN_Scale_Down'], 'true'))
    env:
      ARM_TENANT_ID: $(AZURE-TENANT-ID)
      ARM_CLIENT_ID: $(AZURE-CLIENT-ID)
      ARM_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)

  - script: |
      cd src/terraform/examples/vfxt/${{ parameters.run_terraform }}
      
      tf_destroy_rc=111111
      for i in {1..5}; do
        terraform destroy -auto-approve
        tf_destroy_rc=$?
        if [ "${tf_destroy_rc}" -ne 0 ]; then
          sleep 20
          echo "##vso[task.logissue type=warning;]Terraform destroy did not work. Attempt $i of 5."
        else
          break
        fi
      done
    displayName: 'Terraform Destroy'
    condition: always()
    env:
      ARM_TENANT_ID: $(AZURE-TENANT-ID)
      ARM_CLIENT_ID: $(AZURE-CLIENT-ID)
      ARM_CLIENT_SECRET: $(AZURE-CLIENT-SECRET)
      ARM_SUBSCRIPTION_ID: $(AZURE-SUBSCRIPTION-ID)